name: CI
on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'readme.md'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[skip ci]') == false 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get Count
        run: |
          cd icons
          echo count=$(ls -l |grep "^d"|wc -l) >> $GITHUB_ENV
          cd ..
          echo date1=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d') >> $GITHUB_ENV
          echo date=$(TZ=':Asia/Shanghai' date '+%Y.%m.%d %H:%M') >> $GITHUB_ENV
          echo tag=beta >> $GITHUB_ENV

      - name: Pack
        run: |
          chmod 755 ./.github/pack.sh
          ./.github/pack.sh
      - name: Upload Release Asset
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ env.tag }}
          prerelease: true
          title: ${{ env.date1 }}
          files: outputs/

      - name: upload
        run: |
          cd outputs
          path=$1
          files=$(ls $path)
          for filename in $files
          do
          curl -T $filename -u ${{secrets.coding_password}} "https://emuiicons-generic.pkg.coding.net/files/zip/$filename?version=latest"
          done
      - name: Push changelog
        run: |
          curl -i -X POST -H 'Content-type':'application/json' -d '{"token":"${{secrets.push_token}}","title":"鸿蒙-EMUI完美图标更新通知","content":" **鸿蒙-EMUI完美图标更新了** \n \n **更新时间：${{ env.date }}** \n \n **更新内容** \n \n ``` \n \n ${{ github.event.head_commit.message }} \n \n ``` \n \n by ` ${{ github.event.head_commit.author.name }} ` \n \n [查看详细更新内容](${{ github.event.head_commit.url }}) \n \n 可前往[emui.iconsx.tech](https://emui.iconsx.tech/)进行更新","topic":"EMUI","template":"markdown"}' http://www.pushplus.plus/send